### ISSUE TITLE
[BUG] Calling YubiKeyDeviceListener.Instance.Dispose() does bad things

### ISSUE THREAD

**Issue by canton7** [Yubico/Yubico.NET.SDK#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`YubiKeyDeviceListener` is supposed to be a singleton, and there is no way to create an instance yourself.

However, it is possible to call `YubiKeyDeviceListener.Instance.Dispose()`.

This will dispose the `RwLock` but won't stop the background thread. This means that the next time that something happens to a Yubikey, `Update` will try and enter `RwLock`, and that will throw an exception from a background thread, which will terminate the application.

This isn't particularly serious, as it's a case of "Doctor it hurts when I poke it " / "Don't poke it then", but if an object is supposed to be a singleton instance, it probably shouldn't expose a `Dispose` method, particularly when trying to call that method results in your application terminating.

(And if it does expose a `Dispose` method, that should probably take steps to carefully tear down the background thread (I notice `_isListening` is unused), unsubscribe from events, etc).

### Expected Behavior

Classes shouldn't expose an API which should never be called, and if called, terminate the application.

### Steps To Reproduce

1. Call `YubiKeyDeviceListener.Instance.Dispose();`
2. Plug/Unplug a Yubikey

### Version

1.9.0

### Version

5.4.3

**Comment by DennisDyallo** [comment]
Thanks for bringing this one as well. There have been changes to the YubikeyDeviceListener class that are currently in `develop` that you may review if you like. Here's that PR #89 . I havent looked into it to see address this issue but I'll add it to our internal issue tracking to review before making the release.

**Comment by canton7** [comment]
Cheers, I'll take a look soon.

**Comment by canton7** [comment]
Aha, that does look like a big improvement.

One remark is that the singleton instance isn't thread-safe (and the normal C# convention is that `static` stuff is thread-safe unless stated otherwise)

**Comment by DennisDyallo** [comment]
Hi again! 
I understand that the class currently isnt thread-safe. I'd prefer to close this issue and add that to the backlog. Kind of busy for this years Q4 so got to keep my priorities clear and desk clean 😅
Thanks for your valuable feedback @canton7
