### ISSUE TITLE
Secp256k1/Curve25519 support for PIV auth-sign

### ISSUE THREAD

**Issue by jpopesculian** [Yubico/Yubico.NET.SDK#15]
[In the docs it seems there is no support for Secp256k1 or Curve25519](https://github.com/Yubico/Yubico.NET.SDK/blob/main/Yubico.YubiKey/docs/users-manual/application-piv/apdu/auth-sign.md). As far as I understand [5.2.3+ should support these curves](https://www.yubico.com/blog/whats-new-in-yubikey-firmware-5-2-3/). Is there be support for these curves (without going through PGP)?

**Comment by GregDomzalski** [comment]
Hi @jpopesculian 

No. These algorithms are only supported by the OpenPGP application of the YubiKey. The PIV application only implements the algorithms listed on the first page that you have linked.

Sorry!
