### ISSUE TITLE
[Question]: <title> ClientDataHash Property taking a max of only 32 bytes

### ISSUE THREAD

**Issue by gobimages** [Yubico/Yubico.NET.SDK#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I am trying to test the bulk creation of fido keys in Entra ID. when i call the entra API to create the credential option. the challenged that is sent is very large and i am unable to pass that to the add that to the clientDataHash value and get an error that states System.InvalidOperationException: 'Wrong length.'

i am using the below to convert the string to bytearray

var challenge = DataTransform.Base64UrlToByteArray(configBuilders.publicKey.challenge);
public class DataTransform
{
    public static ReadOnlyMemory<byte> Base64UrlToByteArray(string b64urlString)
    {
        // Replace URL-safe characters
        string temp = b64urlString.Replace("_", "/").Replace("-", "+");

        // Add padding if necessary
        int padding = temp.Length % 4;
        if (padding != 0)
        {
            temp = temp.TrimEnd('=');
            temp += padding % 2 > 0 ? "=" : "==";
            return Convert.FromBase64String(temp.Normalize(NormalizationForm.FormC));
        }

        // Decode Base64 URL
        return Convert.FromBase64String(temp);
    }
}

pass the returned value 

 var makeCredentialParams = new MakeCredentialParameters(
     new RelyingParty(configBuilders.publicKey.rp.id), userEntity, "public-key", Yubico.YubiKey.Fido2.Cose.CoseAlgorithmIdentifier.ES256)
 {
     ClientDataHash = challenge
    

 };

**Comment by GregDomzalski** [comment]
Yeah, the `ClientDataHash` is definitely one of the more confusing parts. @DennisDyallo @dainnilsson Definitely an excellent candidate for a helper class / function. I know @AaFortner and @jamiehankins have a well factored implementation that could probably be lifted into the SDK.

Please read the following section of the Webauthn spec: [5.8.1.1 Client Data JSON: Serialization](https://www.w3.org/TR/webauthn-2/#clientdatajson-serialization).

Construct the payload according to that spec and then run it through a `SHA256` hash, and there you have your `ClientDataHash`.

It basically looks like this:

```csharp
static class ClientData
{
    public byte[] CreateHash(string challenge, string origin, bool crossOrigin = false)
    {
        var result = new StringBuilder();

        // Append the type. Should always be "webauthn.create" for MakeCredential operations
        result.Append("{\"type\":\"webauthn.create\"");
        // Append the challenge
        result.Append($",\"challenge\":\"{challenge}\"");
        // Append the origin (RP)
        result.Append($",\"origin\":\"{origin}\"");
        // Append crossOrigin. 'true' if explicitly 'true', 'false' otherwise.
        result.Append($",\"crossOrigin\":\"{crossOrigin.ToString()}\");
        result.Append("}");

        // Hash the data
        return SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString()));
    }
}
```

The above code is only meant to serve as an example. I typed it out in GitHub - I did not compile or test it. If you read the spec, the implementation is slightly more involved. If you want to be robust, you should implement the spec more precisely. I simply threw something together for illustrative purposes.

I hope the code and the pointer to the spec is helpful!

**Comment by gobimages** [comment]
This definitely helped. Thank you very much. it would be great if there are helper functions added that could assist in the creation of the keys. Re-Reading the documentation now makes more sense
