### ISSUE TITLE
[Question]: Get YubiKey picture based on the serial number?

### ISSUE THREAD

**Issue by bplatypus** [Yubico/Yubico.NET.SDK#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Is there a way to get a picture (ie: image url) of the connected YubiKey device based on it's serial number (or other device info)?
Thanks.

### Context

We wanted to display a picture of the connected device in our application.

**Comment by DennisDyallo** [comment]
Hi! Not based on serial number. But you could look at the [FormFactor](https://github.com/Yubico/Yubico.NET.SDK/blob/a6e1b42aeb399e0def8d001407c01544566f81d8/Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDeviceInfo.cs#L74). It will tell you which formfactor the Yubikey has. 

You could use FormFactor (e.g. USB-C) IsSkySeries (true|false) IsFipsSeries (true|false) and FirmwareVersion to construct a view model. The Yubikey Authenticator has similar logic and shows you which devices are plugged in with a nice little icon representation for each key.

perhaps @dainnilsson knows where one could get those graphics, if available 

It

**Comment by DennisDyallo** [comment]
Here are some graphics that you could use. 
@bplatypus 
https://brandfolder.yubico.com/yubico/press-room-images-logos

**Comment by bplatypus** [comment]
Thanks, I'll have a look.

**Comment by bplatypus** [comment]
for those interested, I took the pictures from the 'flutter' project at the end: https://github.com/Yubico/yubioath-flutter/tree/main/assets/product-images

there's also the code to do the image matching.
