### ISSUE TITLE
[BUG] Change PIN and PUK retry counts for PivSession Incorrectly Set

### ISSUE THREAD

**Issue by alanssitis** [Yubico/Yubico.NET.SDK#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling the `TryChangePinAndPukRetryCounts(admin key, pin, count, count, out var x)`, it is not set as expected by the passed value. Instead, it is being set to 0. Tested with USB C and USB A tokens.

### Expected Behavior

Retry count should be properly set.

### Steps To Reproduce

1. Reset the PIV session
2. Call the change PIN and PUK count with default credentials with retry more than 1
3. Verify the PIN with incorrect PIN -> fails and claims no retries left on first attempt

### Version

1.11.0

### Version

5.7.1 and 5.4.3

### Anything else?

Tested on multiple tokens

**Comment by igalfsg** [comment]
Tested on Both MacOS and Linux. Did not test on Windows

**Comment by DennisDyallo** [comment]
Hi guys!

You mean like this?
![image](https://github.com/user-attachments/assets/373e85ee-06c2-4456-97e5-2c10d18a5911)

**Comment by alanssitis** [comment]
Yes! We are calling it the exact same way but with different retry values (3, 3).

**Comment by DennisDyallo** [comment]
Ok, strange. As you can see it passed for me on a 5.4.3 key.
Are you getting any interesting logs you can share?

**Comment by alanssitis** [comment]
We are using `VerifyPin()` instead and passing the PIN via a KeyCollector, so that's the only difference I can notice. It says that it uses `TryVerifyPin` under the hood. Let me know if this is useful information!

**Comment by alanssitis** [comment]
I just now looked at the source code. The way we setup the `KeyCollector` means that calling `VerifyPin()` would block the PIN if incorrect.

Sorry for the bad issue.
