### ISSUE TITLE
[BUG] Device info for SKY EE keys doesn't have IsSkySeries set when announced via YubiKeyDeviceListener

### ISSUE THREAD

**Issue by AaFortner** [Yubico/Yubico.NET.SDK#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Device info objects surfaced via the YubiKeyDeviceListener have IsSkySeries set to false for SKY Enterprise Edition keys

### Expected Behavior

IsSkySeries is true

### Steps To Reproduce

* Listen for YubiKey device arrival events via YubiKeyDeviceListener.Attach
* Attach an Enterprise Edition Security Key
* Inspect IsSkySeries on the device

### Version

1.12.0-prerelease.20240813

### Version

5.7.1

### Anything else?

Issue is in YubiKeyDeviceInfo.Merge, which isn't setting IsSkySeries on the new info object. Non-Enterprise SKY keys don't have this issue because they only have the HidFido transport an so don't run through Merge. SKY EE keys have both HidFido and SmartCard.

**Comment by DennisDyallo** [comment]
Thanks @AaFortner , will add that to the internal tracker. I'm a bit swamped right now, focusing on getting SCP11 and Ed25519 key support out, as well as some much needed refactor. Feel free to suggest changes if you have the time. Thanks!
