### ISSUE TITLE
Fido2 is internal? 

### ISSUE THREAD

**Issue by zjbpku** [Yubico/Yubico.NET.SDK#18]
All classes in fido2 are internal, why?

**Comment by GregDomzalski** [comment]
The FIDO2 implementation that is there is quite incomplete. This code predates the 1.0 release - we had originally anticipated completing it shortly thereafter (in 1.1) but that never came to be. In retrospect, we probably should have held the code back until it was truly ready.

The good news is that the team is actively working on implementing FIDO2 as we speak. We plan to release the first core bits of FIDO2: MakeCredential, GetAssertion, and PIN management in our upcoming September/October 1.5.0 release. Over the next few releases (likely 1.6 and 1.7) we will try and complete out the support for things like extensions (cred management, etc.) and biometrics support.

**Comment by GregDomzalski** [comment]
Hi @zjbpku - we have released the first batch of FIDO2 features. We now support the PIN protocols, as well as MakeCredential and GetAssertion. We will continue to add additional support for the specification in future releases.

I'm closing this issue now - if you have further questions or concerns, please feel free to open additional issues.
