### ISSUE TITLE
Possiblity of porting to Java/rust?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [Yubico/Yubico.NET.SDK#22]
I wanted to use challenge-response algorithms for my own homemade desktop app
using the api shown in.
https://docs.yubico.com/yesdk/users-manual/application-otp/challenge-response.html

Is it possible?Or is there any similar api?

**Comment by GregDomzalski** [comment]
Hi @RESDXChgfore9hing,

I think the quickest way forward for you would be to look at using our C library for the OTP application: https://github.com/Yubico/yubikey-personalization

You could write some bindings using JNI for Java or using Rust's FFI capabilities.

You would use `ykp_write_config` to write the challenge response config to a particular slot - or you could just use one of our existing tools like `ykman`.

To compute the response given a challenge, you would use `yk_challenge_response`.

You can see an example command line app for computing a chal/resp here: https://github.com/Yubico/yubikey-personalization/blob/master/ykchalresp.c

Hope this helps!

**Comment by RESDXChgfore9hing** [comment]
thanks noted will try it out.
