### ISSUE TITLE
C++ binding needed for Windows and Linux

### ISSUE THREAD

**Issue by patlecat** [Yubico/Yubico.NET.SDK#23]
C++ binding needed for Windows and Linux, basically :)

**Comment by GregDomzalski** [comment]
Hi @patlecat,

What applications of the YubiKey are you interested in using?

Are you aware of our C-based libraries? These would probably be your quickest path forward to working with the YubiKey in C++:

- OTP: https://github.com/Yubico/yubikey-personalization
- PIV: https://github.com/Yubico/yubico-piv-tool/tree/master/lib
- OpenPGP: (Use the GnuPG libraries)
- FIDO: https://github.com/Yubico/libfido2
- HSM Auth: https://github.com/Yubico/yubihsm-shell/tree/master/ykhsmauth

**Comment by patlecat** [comment]
@GregDomzalski  C binding is fine but a true C++ binding adds a lot of additional convenience and security to it.
Besides I have to admit that your documentation is at best confusing and I can't find certain concepts well explained nor do I see a good overview what each lib (you listed above) does.

I was trying for example to use the OTP service via your cloud service but I can't find how to process the token from the YubiKey in a way to confirm that the answer from the cloud service is valid or not. Things like that.

**Comment by patlecat** [comment]
@GregDomzalski 
I see, but I am trying to process the input from the YubiKey to send to your OTP service. Sending and receiving is simple indeed. But it seems that I need to process the string that comes out of the YubiKey once I press the key because your server doesn't accept it as-is. And I can't find a useful documentation for it anywhere.

Could you help with it please?
