### ISSUE TITLE
YubiKeyDevice.FindAll() returns empty list in Hyper-V VM

### ISSUE THREAD

**Issue by mjfara** [Yubico/Yubico.NET.SDK#25]
YubiKeyDevice.FindAll() returns an empty list in Win10 and Win11 VMs in Hyper-V when a YubiKey is connected.
The Yubico Authenticator app in Windows seems to detect the YubiKey just fine and I am able to write to it.
Is the authenticator app doing anything differently?

**Comment by GregDomzalski** [comment]
Out of curiosity - how are you passing the YubiKey into the Hyper-V VM? Last I checked Hyper-V does not support USB passthrough.

In theory, if Yubico Authenticator can see it, the SDK should too. Let me know how you're connecting the YubiKey to the VM and I should be able to investigate this.

**Comment by mjfara** [comment]
By turning on enhanced session mode:
https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect

.Net Framework v4.8
Yubico.YubiKey v1.4.1

Though I have since given up with Hyper-V, seems to work fine on VMWare.

**Comment by GregDomzalski** [comment]
Ah, OK - that uses RDP's smart card passthrough / sharing mechanism, if I recall correctly. It's definitely not something we've testing this SDK with, but it is an interesting use case. I can put this on our backlog for further testing.

Since you've moved on to VMWare, would it be OK if I closed this issue?

**Comment by mjfara** [comment]
So is the Yubico Authenticator app not using the same SDK?
Yes you can go ahead and close this, thanks.

**Comment by GregDomzalski** [comment]
No, the desktop authenticator is based off of our Python codebase - the same that is used by YubiKey Manager / ykman.
