### ISSUE TITLE
Getting Attestation Object for new FIDO2 credential 

### ISSUE THREAD

**Issue by igalfsg** [Yubico/Yubico.NET.SDK#30]
Hi, 

When Making the FIDO2 credential using the SDK I am trying to also get the attestation object (https://w3c.github.io/webauthn/#sctn-attestation) I know the `MakeCredentialData` has all the information required to create my own but wanted to double check if the SDK had a function I missed that I could use before encoding my own Attestation object.

Thanks in advance

**Comment by GregDomzalski** [comment]
No, I don't think the SDK unpacks that all for you. What you get in MakeCredentialData and AuthenticatorData is all that is available in this release.

**Comment by igalfsg** [comment]
ok thanks :)
