### ISSUE TITLE
EcdsaVerify throws UnsupportedAlgorithm exception on .Net Framework

### ISSUE THREAD

**Issue by GregoryMajor** [Yubico/Yubico.NET.SDK#36]
Based on the FIDO2 example placed in this repository I created a client which creates and verifies a credential with YubiKey. 
Under .NET Core 6.0 it works well. Under .NET Framework 4.7.2 and 4.8 the Yubico.YubiKey.Cryptography.EcdsaVerify class throws UnsupportedAlgorithm exception from the CheckECDsa method.

It happens after creating a credential and trying to verify the attestation and verifying the assertion during authentication as well. 
Making it impossible to properly verify the results.

The problem occurs not just with a Fido2Session but with an U2fSession as well. 
(On .NET Framework the U2fSession related code worked with the 1.4.1 YubiKey SDK version.)

According to my investigation, when the CheckECDsa is called the ECDsa object has a proper OID (the ECDsa.Curve.Oid.Value is properly filled with the 1.2.840.10045.3.1.7 value). 
But when the CheckECDsa method calls the toCheck.ExportParameters(false); method, the result 
(ECParameters) eccParams.Curve.Oid.Value property is 'null'. The eccParams.Curve.Oid will still exist and it still carries the name of the algoritm. It seems only the Value property is lost.
(Yubico.YubiKey.Cryptography.EcdsaVerify, line: 404)

This is why the method throws UnsupportedAlgorithm exception.

**Comment by GregDomzalski** [comment]
Hi @GregoryMajor - Version 1.6.1 has been released and contains a fix for this issue. Please let us know if you still encounter it after upgrading, or if you run into any similar sort of errors.

Closing this issue, but feel free to re-open if issue persists.
