### ISSUE TITLE
"No Yubikey interface available" when enabling All interfaces

### ISSUE THREAD

**Issue by steven-keller** [Yubico/Yubico.NET.SDK#42]
I'm using the Yubico.Core and Yubico.Yubikey Nuget packages for setting/removing Lock Codes and add/remove NFC/USB Capabilities.   The SetEnabledUSBCapabilities and SetEnabledNFCCapabilities methods work fine when starting with a Yubikey that initially has all capabilities enabled and then removing all but the FIDO2 NFC/USB capabilities.  However, when I try to re-enable "All" capabilities on that Yubikey, I get "There is no YubiKey interface available to communicate with the requested application".

They YKMan.exe utility and the YKMan-GUI do not have this problem, so it's certainly possible to do this using other means.  Is there some method I need to run prior to the lines of code below, or is this a bug in the SDK?  

device.SetEnabledNfcCapabilities(YubiKeyCapabilities.All);
device.SetEnabledUSBCapabilities(YubiKeyCapabilities.All);

**Comment by GregDomzalski** [comment]
Is this on Windows? If so, you need to run your code in an elevated process.

Windows prevents unprivileged access to any CTAP devices.

**Comment by GregDomzalski** [comment]
Hey @steven-keller - were you able to get logging turned on? Did that show any errors or warnings that might be helpful?

**Comment by GregDomzalski** [comment]
Yes, sorry about that. I just realized that we don't really have a good writeup in our documentation. We ought to correct that.

I believe you would need the following packages:
- Serilog
- Serilog.Sinks.Console
- Serilog.Extensions.Logging

I hope that helps!

**Comment by GregDomzalski** [comment]
Hey @steven-keller - any update on your side? I was never able to reproduce this on my end. Are you still encountering this issue?

**Comment by GregDomzalski** [comment]
Closing this issue. Feel free to re-open it if you are still encountering the issue.
