### ISSUE TITLE
In [Yubico.YubiKey.YubiKeyDevice]::FindByTransport, YubiKeyDeviceListener.Instance isn't disposed ?

### ISSUE THREAD

**Issue by zyyanfei** [Yubico/Yubico.NET.SDK#44]
In [Yubico.YubiKey.YubiKeyDevice]::FindByTransport, 
YubiKeyDeviceListener.Instance isn't disposed explicitly so that the background listener thread won't be end after the call FindByTransport. Each call for FindByTransport will create a new background thread.

**Comment by GregDomzalski** [comment]
Thanks. Will take a look.

**Comment by zyyanfei** [comment]
Thank you Greg. I htink you are right. I looked into this part of code when I tried to investigate the high memory/CPU issue #37. Let's close this ticket.
