### ISSUE TITLE
"Warning, state of non-volatile memory is unchanged." when trying to configure static password or delete slot.

### ISSUE THREAD

**Issue by MartinTeichler** [Yubico/Yubico.NET.SDK#48]
Hello,

I get the above error when trying to configure a static password or delete a slot. This error happens only when I proceed in a specific way:

1. Configure a static password using the [last example from this PDF](https://developers.yubico.com/windows-apis/Releases/yubikey-configuration-API-2.3.pdf) (version 2.2):
        
        // Clear current settings.
        yk.ykClear();

        // Use selected config.
        yk.ykFlagProperty(ykFlagProperty.SECOND_CONFIG) = (slot == 2);

        // Don't append enter at the end.
        yk.ykFlagProperty(ykFlagProperty.APPEND_CR) = false;

        // Use static password mode => output scancodes (as opposed to modhex).
        yk.ykFlagProperty(ykFlagProperty.STATIC_TICKET) = false;

        // Use short ticket.
        yk.ykFlagProperty(ykFlagProperty.SHORT_TICKET) = true;

        // Encode plain text into keyboard scan codes.
        var scanCodes = text2scancode(input);

        // Split key to fit in various yubikey properties.
        var key1 = scanCodes.substr(0, FIXED_SIZE * 2);
        var key2 = scanCodes.substr(FIXED_SIZE * 2, UID_SIZE * 2);
        var key3 = scanCodes.substr(FIXED_SIZE * 2 + UID_SIZE * 2);

        // Set key parts.
        yk.ykStaticId = key1;
        yk.ykUID = key2;
        yk.ykKey = key3;

        // Write config to YubiKey.
        var programResult = yk.ykProgram;

3. Without removing the Yubikey, use the current .Net SDK to configure a static password:

        public void SendStaticPasswordToYubikey(IYubiKeyDevice yubikey, Memory<char> payload, int slot)
        {
            if (slot != 1 && slot != 2)
                throw new ArgumentException($"{nameof(slot)} has to be either 1 or 2.");

            using (var otp = new OtpSession(yubikey))
            {
                var castSlot = (Slot)slot;

                if (castSlot == Slot.LongPress && otp.IsLongPressConfigured)
                    otp.DeleteSlot(Slot.LongPress);
                else if(castSlot == Slot.ShortPress && otp.IsShortPressConfigured)
                    otp.DeleteSlot(Slot.ShortPress);

                otp.ConfigureStaticPassword((Slot)slot)
                    .WithKeyboard(KeyboardLayout.en_US)
                    .SetPassword(payload)
                    .Execute();
            }
        }
   
The call to Execute will throw the above error. Is there any way to "fix" this? I tried deleting the slot, but I get the same error. The only way to make it go away is to delete the slot (which leads to the above error) and restart the program. After that, it will write to the key successfully.

**Comment by GregDomzalski** [comment]
And you say this _only_ happens if you provision with the COM code first?

As in: If you did not use COM, but configured the slot using the .NET SDK first and then try to re-run it on the same YubiKey, would that work fine?

How quickly is the .NET code running after the COM code is run?

Lastly, what version of the .NET SDK are you using?

**Comment by MartinTeichler** [comment]
> And you say this _only_ happens if you provision with the COM code first?
> 
> As in: If you did not use COM, but configured the slot using the .NET SDK first and then try to re-run it on the same YubiKey, would that work fine?

Yes and yes. What I noticed too was that the serial was not displayed when I wrote a static password using COM api. It doesn't really matter whether I wait a few hours or try to send a password immediately, the result is still the same.

I did a bit of digging around and found out that it has to do with the transport I am using. According to the docs, HID keyboard should support most operations. However, sometimes I also get SmartCard and this is where the error occurs. So now, the problem is, I get a SmartCard key and a HID key, but they are returned as two IYubiKey instances and due to the missing serial number, I cannot guarantee that these are the same key. Also, I noticed that I only get a SmartCard when using VMs, which makes kinda sense due to the RDP protocol and how it handles USB passthrough. But this is still a problem because the software needs to work both on host machines and VMs.

**Comment by MartinTeichler** [comment]
`Could there be any background or long running processes that are attempting to communicate with the YubiKey?`

I am not really sure. I am working on a customer laptop and they got all different kinds of programs and background processes running, they basically have a 3rd party app for everything. 

I am not sure that the .Net SDK is even the problem here, I think it's rather the COM api because even when we open Yubikey Manager, the serial numbers are not there after we write a static password to the key. The call to yk.ykProgram seems to be the point of entry for this problem. As you can see in my example above, we are not really doing anything out of the ordinary.

Anyway, I added Serilog to my application. It's a WinForms app so I had to make a few adjustments. However, I don't get any output from your SDK. I can inject an ILogger to my app and log with that, so the logging seems to be working.

```
 var builder = new HostBuilder()
    .ConfigureServices((hostContext, services) =>
    {
        services.AddScoped<Form1>();

        //Add Serilog
        var serilogLogger = new LoggerConfiguration()
            .WriteTo.File("log.log")
            .CreateLogger();
        services.AddLogging(x =>
        {
            x.SetMinimumLevel(LogLevel.Information);
            x.AddSerilog(logger: serilogLogger, dispose: true);
            x.AddFilter(level => level >= LogLevel.Information);
        });
    });

var host = builder.Build();
ApplicationConfiguration.Initialize();
Application.Run(host.Services.GetRequiredService<Form1>());
```

**Comment by GregDomzalski** [comment]
Yes, any kind of logger will do.

You say you're still not getting any output from the SDK? I assume based on your code snippet above that this is run prior to any SDK functionality being invoked?

**Comment by MartinTeichler** [comment]
> Yes, any kind of logger will do.
> 
> You say you're still not getting any output from the SDK? I assume based on your code snippet above that this is run prior to any SDK functionality being invoked?

Yes, that is correct. I only use the Yubikey stuff inside Form1 and that is injected deeper in the pipeline so it should work.

**Comment by DennisDyallo** [comment]
Hey @MartinTeichler ! Are you still experiencing this issue? If not, we'll close the issue. Thanks.

**Comment by DennisDyallo** [comment]
Closing old issues. Feel free to reopen if this is still important to you.
