### ISSUE TITLE
Unfortunately only works for .net software

### ISSUE THREAD

**Issue by Videogamer555** [Yubico/Yubico.NET.SDK#49]
I would like to be able to write standard Windows software (not that which is based on .net) that incorporates Yubikey authentication. Do you have, or will you have at some point, an SDK that supports using Yubikey in standard Windows software?

**Comment by GregDomzalski** [comment]
Can you please elaborate by what you mean by "standard Windows software"? Yubico does have several C based libraries that you can integrate with, depending on what you're trying to do:
OTP: https://github.com/Yubico/yubikey-personalization
PIV: https://github.com/Yubico/yubico-piv-tool
FIDO/Webauthn: https://github.com/Yubico/libfido2

**Comment by GregDomzalski** [comment]
Closing as out of scope for this project.

I'm happy to point you in the right direction with our other libraries if the above C libraries are not what you're looking for.
