### ISSUE TITLE
credBlob and largeBlob support

### ISSUE THREAD

**Issue by barnabas90** [Yubico/Yubico.NET.SDK#56]
Hey, I'm working on a small app that supports passkey registration/authentication and I'd like to try out the credBlob and largeBlob extensions as well. Unfortunately all my yubikeys (series 5) here lack the support for these extensions (according to the sdk's authenticator info class), and I couldn't find any reliable source of information about which yubikeys support these extensions. However I found some hints that the yubikey bio product line might support it, could anyone confirm that information?

**Comment by GregDomzalski** [comment]
Yes, our YubiKey Bio products have newer FIDO implementations than our standard keys.

**Comment by barnabas90** [comment]
Thank you!
