### ISSUE TITLE
Unable to load DLL Yubico.NativeShims or one of its dependencies 

### ISSUE THREAD

**Issue by igalfsg** [Yubico/Yubico.NET.SDK#57]
Hi Gregg,

 We are encountering a very weird error in one of my customer's computers, we are getting 

> Unable to load DLL Yubico.NativeShims or one of its dependencies. The specifed module could not be found. (0x80070007E)

We have tried to replicated it everywhere else and we have not been able to do it. I tried updating to the latest Yubico Library and we were still having the same issue. Do you know if this is a known issue? It was a Windows 11 fresh install. 

Thanks,

**Comment by igalfsg** [comment]
yeah they are using the regular EZSmartCard application (.NET 7), it works for them in all the PCs except one, that is why I find it weird, do you know if there is a way for them to install that dependency externally so we can add it to the troubleshooting, or something I can do in my config to ensure that we install that DLL?

**Comment by GregDomzalski** [comment]
It sounds like they've either corrupted their install, or something just didn't deploy correctly?

The way I would recommend debugging this is having the customer run [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) and filter on your application name and "Yubico.NativeShims".

I would expect you'll see a lot of FILE_NOT_FOUND errors on CreateFile (for when the loader is attempting to find the library). It'll give you some hints as to where the system is attempting to locate the file and why it cannot load the file. (Perhaps you'll see a sharing violation or access denied error as well). If they're all FILE_NOT_FOUND, then the customer should double check those paths to verify that the library is indeed missing.

**Comment by igalfsg** [comment]
oh ok thanks, I will check with them
