### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by grimson73** [Yubico/Yubico.NET.SDK#69]
Hi, just browsing the documentation and noticed a really small typo:

Yubico.YubiKey/docs/users-manual/application-fido2/fido2-credentials.md

> When authenticating to the relying party, the YubiKey will build an assertion by using the private key to sign some data that includes a challenge from the **_relyng_** party.

Thanks! :)

**Comment by DennisDyallo** [comment]
Thank you for your keen eye! It'll make the next documentation update.
