### ISSUE TITLE
Cannot find YubiHSM 2 FIPS v2.2 with YubiKeyDevice.FindAll()

### ISSUE THREAD

**Issue by jwfx** [Yubico/Yubico.NET.SDK#71]
OS: Win10 x64

After installing `yubihsm-connector-windows-amd64.msi` and `yubihsm-shell-x64.msi` interaction with the shell is possible.

Cannot get the device to show up with `YubiKeyDevice.FindAll()` while using `<PackageReference Include="Yubico.YubiKey" Version="1.9.1" />`.

What am I missing?

**Comment by GregDomzalski** [comment]
Hi @jwfx - this SDK only supports our YubiKey product line and not the YubiHSMs.

You would likely need to use our C library here: https://github.com/Yubico/yubihsm-shell

**Comment by jwfx** [comment]
Thanks for the quick response.

I suppose nothing is stopping me from using the `C:\Program Files\Yubico\YubiHSM Shell\bin\libyubihsm.dll` via DllImport?

**Comment by GregDomzalski** [comment]
Yup, I believe that should work.
