### ISSUE TITLE
Can't build  Yubico.NativeShims on osx-arm64 

### ISSUE THREAD

**Issue by thomnico** [Yubico/Yubico.NET.SDK#76]
The error is here: [ 28%] Building C object CMakeFiles/Yubico.NativeShims.dir/ssl.bignum.c.o
/Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/ssl.bignum.c:9:1: error: cannot combine with previous 'type-name' declaration specifier
void Native_BN_new(void)
^
1 error generated. 

See fulll logs bellow :
Yubico.NativeShims % sh build-macOS.sh 
~/vcpkg ~/src/Yubico.NET.SDK/Yubico.NativeShims
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
warning: neither `vcpkg.json` nor `vcpkg-configuration.json` exist to update.
~/src/Yubico.NET.SDK/Yubico.NativeShims
-- Running vcpkg install
Detecting compiler hash for triplet arm64-osx...
Detecting compiler hash for triplet x64-osx...
The following packages will be built and installed:
    openssl[core]:x64-osx -> 3.2.1#2
  * vcpkg-cmake[core]:arm64-osx -> 2023-05-04
  * vcpkg-cmake-config[core]:arm64-osx -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:arm64-osx -> 2023-12-31
Additional packages (*) will be modified to complete this operation.
Restored 4 package(s) from /Users/nicolasthomas/.cache/vcpkg/archives in 471 ms. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:arm64-osx...
Elapsed time to handle vcpkg-cmake:arm64-osx: 2.924 ms
Installing 2/4 vcpkg-cmake-get-vars:arm64-osx...
Elapsed time to handle vcpkg-cmake-get-vars:arm64-osx: 1.837 ms
Installing 3/4 vcpkg-cmake-config:arm64-osx...
Elapsed time to handle vcpkg-cmake-config:arm64-osx: 1.653 ms
Installing 4/4 openssl:x64-osx...
Elapsed time to handle openssl:x64-osx: 51.84 ms
Total install time: 529.3 ms
The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

-- Running vcpkg install - done
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_STACK_PROTECTOR_ALL
-- Performing Test HAVE_STACK_PROTECTOR_ALL - Success
-- -fstack-protector-all support detected
Checking for PCSC with Mac linkage
PCSC_WINSCARD_H_FOUND: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/PCSC.framework/Headers/winscard.h
HAVE_PCSC_WINSCARD_H: ON
PCSC_MACOSX_LIBS: -Wl,-framework -Wl,PCSC
PCSC_LIBRARIES: -Wl,-framework -Wl,PCSC
PCSC_CFLAGS: 
BACKEND_PCSC: ON
HAVE_PCSC_WINSCARD_H: ON
-- Found OpenSSL: /Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/build64/vcpkg_installed/x64-osx/lib/libcrypto.a (found version "3.2.1")
INFOIPO is enabled.
-- Configuring done (4.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/build64
[ 14%] Building C object CMakeFiles/Yubico.NativeShims.dir/pcsc.c.o
[ 28%] Building C object CMakeFiles/Yubico.NativeShims.dir/ssl.bignum.c.o
/Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/ssl.bignum.c:9:1: error: cannot combine with previous 'type-name' declaration specifier
void Native_BN_new(void)
^
1 error generated.
gmake[2]: *** [CMakeFiles/Yubico.NativeShims.dir/build.make:90: CMakeFiles/Yubico.NativeShims.dir/ssl.bignum.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Yubico.NativeShims.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
cp: ./build64/libYubico.NativeShims.dylib: No such file or directory
-- Running vcpkg install
Detecting compiler hash for triplet arm64-osx...
The following packages will be built and installed:
    openssl[core]:arm64-osx -> 3.2.1#2
  * vcpkg-cmake[core]:arm64-osx -> 2023-05-04
  * vcpkg-cmake-config[core]:arm64-osx -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:arm64-osx -> 2023-12-31
Additional packages (*) will be modified to complete this operation.
Restored 4 package(s) from /Users/nicolasthomas/.cache/vcpkg/archives in 431.9 ms. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:arm64-osx...
Elapsed time to handle vcpkg-cmake:arm64-osx: 2.503 ms
Installing 2/4 vcpkg-cmake-get-vars:arm64-osx...
Elapsed time to handle vcpkg-cmake-get-vars:arm64-osx: 3.575 ms
Installing 3/4 vcpkg-cmake-config:arm64-osx...
Elapsed time to handle vcpkg-cmake-config:arm64-osx: 2.219 ms
Installing 4/4 openssl:arm64-osx...
Elapsed time to handle openssl:arm64-osx: 59.69 ms
Total install time: 499.9 ms
The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

-- Running vcpkg install - done
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_STACK_PROTECTOR_ALL
-- Performing Test HAVE_STACK_PROTECTOR_ALL - Success
-- -fstack-protector-all support detected
Checking for PCSC with Mac linkage
PCSC_WINSCARD_H_FOUND: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/PCSC.framework/Headers/winscard.h
HAVE_PCSC_WINSCARD_H: ON
PCSC_MACOSX_LIBS: -Wl,-framework -Wl,PCSC
PCSC_LIBRARIES: -Wl,-framework -Wl,PCSC
PCSC_CFLAGS: 
BACKEND_PCSC: ON
HAVE_PCSC_WINSCARD_H: ON
-- Found OpenSSL: /Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/buildarm/vcpkg_installed/arm64-osx/lib/libcrypto.a (found version "3.2.1")
INFOIPO is enabled.
-- Configuring done (3.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/buildarm
[ 14%] Building C object CMakeFiles/Yubico.NativeShims.dir/pcsc.c.o
[ 28%] Building C object CMakeFiles/Yubico.NativeShims.dir/ssl.bignum.c.o
/Users/nicolasthomas/src/Yubico.NET.SDK/Yubico.NativeShims/ssl.bignum.c:9:1: error: cannot combine with previous 'type-name' declaration specifier
void Native_BN_new(void)
^
1 error generated.
gmake[2]: *** [CMakeFiles/Yubico.NativeShims.dir/build.make:90: CMakeFiles/Yubico.NativeShims.dir/ssl.bignum.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Yubico.NativeShims.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
cp: ./buildarm/libYubico.NativeShims.dylib: No such file or directory

**Comment by GregDomzalski** [comment]
Thanks for the report! Not sure how this one snuck past our CI.

We will address this soon.

**Comment by DennisDyallo** [comment]
Hi! As most people don't build this SDK themselves and we're starved for time, we are not able to prioritize this investigation. I hope to notify you as soon as we pick it up though. 

Thanks for the report.
