### ISSUE TITLE
[Question]: Establish PIV session with device

### ISSUE THREAD

**Issue by briggst1** [Yubico/Yubico.NET.SDK#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I am having difficulty with establishing a PIV session with a key that is already plugged in.

Currently, I have code something like the following.  _Most_ of the time this works fine.  However, sometimes, I get the `System.NotSupportedException` with the what() indicating that a PIV session could not be created.  

Note: I tried using the yubikey listener from the sample code and had similar results: sometimes it would not get PIV session, other times its just fine.

Thoughts?  Something I'm doing / not doing?

```
foreach (var dev in YubiKeyDevice.FindAll())
{
   try {
       System.Threading.Thread.Sleep(125);
       session = new PivSession(dev);
   }
    catch (Yubico.PlatformInterop.SCardException e)
 {
     MessageBox.Show("Error " + e.Message);
     Debug.Write("Error " + e.Message);
     Debug.Write(e.StackTrace);
     return false;
 }
 catch (System.NotSupportedException e)
 {
     MessageBox.Show(e.Message);
     Debug.Write("Error " + e.Message);
     return false;
 }
```

**Comment by DennisDyallo** [comment]
Hi @briggst1 and thanks for checking out the SDK. 

I'm new to the codebase myself but upon first glance it makes me want to direct you to this SDK article on creating and disposting connections: 

https://docs.yubico.com/yesdk/users-manual/sdk-programming-guide/making-a-connection.html#2a-session

Specifically around the opening (and disposing) of a Session. If you follow the steps from this, do you still encounter the same behaviour?

**Comment by GregDomzalski** [comment]
I suspect this could be a manifestation of #72

**Comment by DennisDyallo** [comment]
Are you still experiencing problems @briggst1 ?

**Comment by briggst1** [comment]
Yes, there are still times where, when the YubiKey is already plugged in, then I start my application, I get the same error.  However, instructing the user to remove the key and re-insert, generally works around the problem.

**Comment by DennisDyallo** [comment]
I see. Well, I'm still getting used to the codebase myself, but I think there's more related work that might address the issue. e.g. #89. Once it's merged you can try the latest develop branch and build it yourself/download and reference directly and see if you still experience the issue.

**Comment by DennisDyallo** [comment]
We will continue to work on stability of the SDK. I'm closing this question for now but please feel free to reopen it if the matter worsens. Thank you !
